spring:
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: root
  
mybatis:
  mapper-locations: classpath:com/yhq/ssmdemo/web/mysql/mapper/*.xml
  type-aliases-package: com.yhq.ssmdemo.web.mysql.pojo